CFFLAGS: -std=99	-Wall	-Werror

.PHONY: all clean

all: identificar_matriz_simetrica

identificar_matriz_simetrica: identificar_matriz_simetrica.c
	gcc $(CFFLAGS) identificar_matriz_simetrica.c -o identificar_matriz_simetrica 

clean:
	rm -f identificar_matriz_simetrica

